# Define os serviços da sua aplicação
services:
  # Serviço para a API Spring Boot (femapi)
  - type: web
    name: femapi
    env: docker
    region: oregon 
    plan: free
    
    # Aponta para o Dockerfile que criamos
    dockerContext: ./femapi
    dockerfilePath: ./femapi/Dockerfile

    healthCheckPath: /swagger-ui/index.html
    
    # Pega as credenciais do banco de dados criado abaixo
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: femapi-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: femapi-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: femapi-db
          property: password

# Define o banco de dados da sua aplicação
databases:
  - name: femapi-db
    plan: free # Define o plano gratuito para o banco de dados
    databaseName: femapi # O nome real do banco de dados
    user: femapi_user # O nome do usuário