services:
  # Serviço para a API Spring Boot (femapi)
  - type: web
    name: femapi
    env: docker
    region: oregon # Sinta-se à vontade para mudar a região
    plan: free
    
    # Aponta para o Dockerfile da sua API
    dockerContext: ./femapi
    dockerfilePath: ./femapi/Dockerfile

    healthCheckPath: /swagger-ui/index.html
    
    # As variáveis de ambiente agora se conectarão ao serviço de banco de dados
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://femapi-db:30306/femapi # Porta interna do Render para MySQL
      - key: SPRING_DATASOURCE_USERNAME
        fromService:
          type: pserv
          name: femapi-db
          envVarKey: MYSQL_USER
      - key: SPRING_DATASOURCE_PASSWORD
        fromService:
          type: pserv
          name: femapi-db
          envVarKey: MYSQL_PASSWORD

  # Serviço para o Banco de Dados MySQL com Disco Persistente
  - type: pserv
    name: femapi-db
    region: oregon
    plan: free
    
    # CORREÇÃO: Usando a sintaxe correta para a imagem Docker
    image:
      url: mysql:8.0
    
    # Anexando o disco persistente
    disk:
      name: mysql-data
      mountPath: /var/lib/mysql
      sizeGB: 1
      
    # Variáveis de ambiente para configurar o container do MySQL
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        generateValue: true
      - key: MYSQL_DATABASE
        value: femapi
      - key: MYSQL_USER
        value: render # Você pode usar o nome que preferir
      - key: MYSQL_PASSWORD
        generateValue: true