services:
  - type: web
    name: femapi
    env: docker
    region: oregon
    plan: free
    dockerContext: ./femapi
    dockerfilePath: ./femapi/Dockerfile
    healthCheckPath: /swagger-ui/index.html
    envVars:
      # 1. Construímos a URL PERFEITA a partir das partes individuais
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
      
      # 2. Pedimos ao Render as partes individuais do banco de dados
      - key: DB_HOST
        fromDatabase:
          name: femapi-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: femapi-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: femapi-db
          property: database
      
      # 3. As credenciais continuam as mesmas
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: femapi-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: femapi-db
          property: password

databases:
  - name: femapi-db
    plan: free
    databaseName: femapi
    user: femapi_user