services:
  # Serviço para a API Spring Boot (femapi)
  - type: web
    name: femapi
    # Agora usa o Docker como ambiente de execução
    env: docker
    region: oregon
    plan: free
    
    # Aponta para o Dockerfile que acabamos de criar
    dockerContext: ./femapi
    dockerfilePath: ./femapi/Dockerfile

    # Configurações de Saúde da Aplicação
    healthCheckPath: /swagger-ui/index.html

    # Variáveis de Ambiente para conectar ao banco de dados
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: femapi-mysql
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: femapi-mysql
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: femapi-mysql
          property: password

  # Serviço para o Banco de Dados MySQL
  - type: pserv
    name: femapi-mysql
    # Aponta para uma imagem oficial do MySQL no Docker Hub
    image:
      url: mysql:8.0
    region: oregon
    plan: free

    # Adiciona um disco persistente para não perder os dados
    disks:
      - name: mysql-data
        mountPath: /var/lib/mysql
        sizeGB: 1

    # Variáveis de ambiente para configurar o banco de dados
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        generateValue: true # Gera uma senha segura automaticamente
      - key: MYSQL_DATABASE
        value: femapi # Nome do seu banco de dados
      - key: MYSQL_USER
        value: user # Nome de usuário que você pode escolher
      - key: MYSQL_PASSWORD
        generateValue: true # Gera outra senha segura para o usuário